env: local
http:
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: 1234

data:
  postgres:
    host: ep-yellow-smoke-a1yd0swt-pooler.ap-southeast-1.aws.neon.tech
    user: neondb_owner
    password: npg_JRL1PhwNH5bI
    dbname: neondb
    port: 5432

  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

geoip:
  urls:
    - https://raw.githubusercontent.com/alfuckk/GeoLite.mmdb/refs/heads/download/GeoLite2-ASN.mmdb
    - https://raw.githubusercontent.com/alfuckk/GeoLite.mmdb/refs/heads/download/GeoLite2-City.mmdb
    - https://raw.githubusercontent.com/alfuckk/GeoLite.mmdb/refs/heads/download/GeoLite2-Country.mmdb
  data_path:  ./storage/mmdb

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30              # 日志文件最多保存多少个备份
  max_age: 7                   #  文件最多保存多少天
  max_size: 1024               #  每个日志文件保存的最大尺寸 单位：M
  compress: true               # 是否压缩